### ISSUE TITLE
薄丘尼的三联画摆放产生误解

### ISSUE THREAD

**Issue by Yulatu** [Editi0/150-Years-of-Modern-Art#1]
未来主义薄丘尼的三联画有两组同名的《心境》共六幅，可参考：https://www.wikiart.org/en/Search/States%20of%20Mind

**Comment by Editst** [comment]
感谢指正，不过根据 MoMA 的页面，应该只有一组，目前配图中的第二张有误。

[Umberto Boccioni](https://www.moma.org/artists/624)
[States of Mind II: Those Who Go](https://www.moma.org/collection/works/78653)
